### ISSUE TITLE
Zooming stopped working

### ISSUE THREAD

**Issue by arunge** [Pandora-IsoMemo/TraceR#17]
From https://github.com/Pandora-IsoMemo/TraceR/pull/15#issue-2375493291

> I realized that the zooming feature which was added trough the panzoom js library is not working anymore. I don't know the reason but did not want to spend much time on it.

- [x] check and fix zooming

**Comment by f-lukas** [comment]
I have realized that the zooming stopped working again in cases where a json is uploaded that renders a graph. Therefore I reopen here.
