### ISSUE TITLE
Download a json with signature

### ISSUE THREAD

**Issue by arunge** [Pandora-IsoMemo/TraceR#20]
This is the first part of https://github.com/Pandora-IsoMemo/TraceR/issues/14#issue-2359921686

> **IMPORTANT:** Signing a file will be possible only in the [online version](https://pandoraapp.earth/app/tracer-beta) of the app!
> 
> In the **online** version during ["Export with signature"](https://github.com/Pandora-IsoMemo/TraceR/issues/11#issue-2359673989):
> - the current userID (comming from the login handled via shinyproxy) must be saved and added to the `.json` file
> - the content of the .json will be signed using `openssl::rsa_keygen()`, compare https://github.com/Pandora-IsoMemo/TraceR/pull/10/files
>   - before hosting the app we will generate `private` and `public` keys that will only live on our shinyproxy server (and in a tool for storing passwords/credentials...)
>   - when the app is running online, we can create a signature (`openssl::signature_create()`) using our private key (via an environment variable) for our file to be exported
>   - export of the file containing the signature

@f-lukas as discussed, please
- [x] first test & merge the PR: https://github.com/Pandora-IsoMemo/TraceR/pull/19
- [x] add a new button to download a signed `.json` file (hidden when not running the online version) and feel free to open sub-issues as needed

**Comment by f-lukas** [comment]
I am closing here as the signed download is now available in the beta app.
