### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by f-lukas** [Pandora-IsoMemo/TraceR#3]
## CI

- [x] add Dockerfile
- [x] add Jenkinsfile
- [x] dockerignore & Rbuildignore

## Deployment

- [x] Create beta Branch
- [x] add gh actions to push into docker registry
- [x] add TraceR to [pull-docker-images job](https://www.isomemodb.com/jenkins/job/pull-docker-images/configure)
- [x] add TraceR to `/etc/shinyproxy/application.yml`

@jan-abel-inwt could you please take care of this ticket. I also added a few files but please check if everything is correct. Could you also please create a beta branch and also do the deployment for the beta branch. Thanks!  And one more thing: The main branch currently contains the package structure but no shiny app yet.

**Comment by jan-abel-inwt** [comment]
You can find both version of the app under these links:

https://pandoraapp.earth/app/tracer
https://pandoraapp.earth/app/tracer-beta

Also i linked a PR with a small change to the Dockerfile
