### ISSUE TITLE
Align main & beta versions

### ISSUE THREAD

**Issue by jan-abel-inwt** [Pandora-IsoMemo/TraceR#9]
- [x] merge beta into main -> https://github.com/Pandora-IsoMemo/TraceR/pull/18
- [ ] deploy main version on shinyproxy

**Comment by arunge** [comment]
@jan-abel-inwt I think we can close here. Both versions are up-to-date and online:
- https://pandoraapp.earth/app/tracer
- https://pandoraapp.earth/app/tracer-beta
